# Generated by Django 4.2.3 on 2023-07-14 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 13, 54, 26, 640201, tzinfo=datetime.timezone.utc)),
        ),
    ]
